
/*-----------------------------------------------------*/
//  Plugin to stick content to the bottom of the page
/*-----------------------------------------------------*/
(function($){$.fn.stickTop=function(objOffset){var obj,topPos,thisTopPos,pos,anyMargin,anyPadding,newPadding;return this.each(function(){obj=$(this);obj.css({'top':'0','position':'relative'});if(!objOffset)objOffset=0;topPos=obj.offset().top;var hoverOutPos=0;obj.hover(function(){if($('body').is('.no-mobile')){$(this).stop().animate({top:'0px',backgroundColor:'#fff'},150);}},function(){if($('body').is('.no-mobile')){$(this).stop().animate({top:hoverOutPos+'px'},150,function(){if(pos>141){$(this).css('background-color','transparent')}});}});obj.click(function(){if($('body').is('.mobile') && !$('nav').is('.openNav')){$('nav').addClass('openNav').stop().animate({top:'0px',backgroundColor:'#fff'},150);return false;}else{$('nav').removeClass('openNav').stop().animate({top:hoverOutPos+'px'},150,function(){if(pos>23){$(this).css('background-color','transparent')}});}}); anyPadding=parseInt(obj.next().css('paddingTop').replace('px',''),'decimal');function adjustResolution(){obj.stop();thisTopPos=topPos+objOffset*(-1);pos=(window.pageYOffset||document.documentElement.scrollTop);if(pos>thisTopPos){hoverOutPos=objOffset;obj.css({'top':objOffset+'px','position':'fixed','background-color':'transparent'}).removeClass('openNav').addClass('delay');newPadding=parseInt(obj.outerHeight(),'decimal');anyMargin=parseInt(obj.next().css('marginTop').replace('px',''),'decimal');if(anyMargin)newPadding+=anyMargin;if(anyPadding)newPadding+=anyPadding;obj.next().css('paddingTop',newPadding+'px')}else if(pos<=thisTopPos){hoverOutPos=0;obj.css({'position':'relative','top':'0','background-color':'#fff'}).addClass('openNav').removeClass('delay');obj.next().css('paddingTop',anyPadding+'px')}}adjustResolution();$(window).bind('scroll resize',adjustResolution)})}})(jQuery);

/*-----------------------------------------------------*/
//  Plugin to stick content to the bottom of the page
/*-----------------------------------------------------*/
(function($){$.fn.stickBot=function(objOffset){var obj,botPos,thisBotPos,pos;return this.each(function(){obj=$(this);obj.css({'bottom':'0','position':'relative'});botPos=obj.offset().top;var parentMarginTop=parseInt(obj.parent().css('marginTop'),'decimal');if(parentMarginTop){botPos+=parentMarginTop}var allPadding=0;obj.parent().children().each(function(){allPadding+=parseInt($(this).css('paddingBottom').replace('px',''),'decimal')});if(allPadding){botPos+=allPadding}if(!objOffset)objOffset=0;var hoverOutPos=0;obj.hover(function(){$(this).stop();$(this).animate({bottom:'0px'},150)},function(){$(this).stop();$(this).animate({bottom:hoverOutPos+'px'},150)});var size=obj.outerHeight(true);if(obj.parent().hasClass('harscrollWrap')){}else{obj.wrap('<div class="harscrollWrap" style="height:'+size+'px" />')}function adjustResolution(){thisBotPos=botPos+objOffset*(-1);pos=$(document).scrollTop();pos+=$(window).height();pos+=obj.height();if(pos>thisBotPos){hoverOutPos=0;obj.css({'bottom':'auto','position':'relative','z-index':920});obj.find('a').css('backgroundImage','url('+base_url+'assets/images/structure/float_nav_dots.png)')}else if(pos<=thisBotPos){hoverOutPos=objOffset;obj.css({'bottom':objOffset+'px','position':'fixed','z-index':900});obj.find('a').css('backgroundImage','none')}}adjustResolution();$(window).bind('scroll resize',adjustResolution)})}})(jQuery);



